/* Types for confetti.js (generated by Confetti Studio, kept verbatim). */
export const CONFIG: Record<string, unknown>

export function confetti(
  canvas: HTMLCanvasElement,
  options?: {
    spec?: Record<string, unknown>
    loop?: boolean
    speed?: number
    transparent?: boolean
    respectReducedMotion?: boolean
    onComplete?: () => void
  },
): () => void
