/* Confetti — generated by Confetti Studio.
 * Self-contained, no dependencies. Canvas 2D, deterministic (seeded).
 *
 *   import { confetti } from './confetti.js'
 *   const stop = confetti(document.querySelector('canvas'), { loop: false })
 *   // stop() cancels the animation and releases the frame loop.
 */

export const CONFIG = {
  "canvas": {
    "aspect": "wide",
    "background": "#f9f9fa",
    "trail": 0
  },
  "emitter": {
    "shape": "point",
    "x": 0.5,
    "y": 0.27,
    "width": 0.6,
    "height": 0.1,
    "angle": 0,
    "spread": 360,
    "count": 220,
    "duration": 0.6,
    "explosiveness": 0.85
  },
  "launch": {
    "power": 900,
    "powerVar": 0.55
  },
  "physics": {
    "gravity": 1400,
    "drag": 0.55,
    "wind": 0,
    "swayAmp": 30,
    "swayFreq": 1.6,
    "turbulence": 120
  },
  "rotation": {
    "spin": 320,
    "spinVar": 0.8,
    "flutter": 1.4,
    "flutterVar": 0.7,
    "alignToVelocity": false
  },
  "shape": {
    "size": 15,
    "sizeVar": 0.5,
    "ratio": 0.45,
    "rect": 45,
    "circle": 25,
    "ribbon": 20,
    "triangle": 10
  },
  "life": {
    "life": 2.6,
    "lifeVar": 0.4,
    "fadeIn": 0.05,
    "fadeOut": 0.7,
    "fadeEase": "cubicOut",
    "scaleStart": 1,
    "scaleEnd": 1,
    "scaleEase": "linear"
  },
  "look": {
    "opacity": 1,
    "shine": true
  },
  "palette": {
    "count": 8,
    "c1": "#00CEE6",
    "c2": "#FFBB38",
    "c3": "#18A957",
    "c4": "#DF1642",
    "c5": "#8158EC",
    "c6": "#FA715F",
    "c7": "#2A90D8",
    "c8": "#6368DB"
  },
  "random": {
    "seed": 7,
    "chaos": 1
  }
}

const TAU = Math.PI * 2
const DEG = Math.PI / 180
const FIXED_DT = 1 / 120
const REFERENCE_HEIGHT = 900

const EASINGS = {
  linear: (t) => t,
  sineOut: (t) => Math.sin((t * Math.PI) / 2),
  quadOut: (t) => 1 - (1 - t) * (1 - t),
  cubicOut: (t) => 1 - Math.pow(1 - t, 3),
  expoOut: (t) => (t >= 1 ? 1 : 1 - Math.pow(2, -10 * t)),
  backOut: (t) => 1 + 2.7 * Math.pow(t - 1, 3) + 1.7 * Math.pow(t - 1, 2),
  quadIn: (t) => t * t,
  cubicIn: (t) => t * t * t,
  sineInOut: (t) => -(Math.cos(Math.PI * t) - 1) / 2,
}
const ease = (k, t) => (EASINGS[k] || EASINGS.linear)(t)
const clamp01 = (v) => (v < 0 ? 0 : v > 1 ? 1 : v)

function makeRng(seed) {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) >>> 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function palette(spec) {
  const all = [spec.palette.c1, spec.palette.c2, spec.palette.c3, spec.palette.c4,
               spec.palette.c5, spec.palette.c6, spec.palette.c7, spec.palette.c8]
  return all.slice(0, Math.max(1, Math.min(8, Math.round(spec.palette.count))))
}

function pickShape(spec, r) {
  const s = spec.shape
  const total = s.rect + s.circle + s.ribbon + s.triangle
  if (total <= 0) return 'rect'
  const t = r * total
  if (t < s.rect) return 'rect'
  if (t < s.rect + s.circle) return 'circle'
  if (t < s.rect + s.circle + s.ribbon) return 'ribbon'
  return 'triangle'
}

function build(spec, W, H) {
  const rng = makeRng(Math.round(spec.random.seed))
  const chaos = Math.max(0, spec.random.chaos)
  const colors = palette(spec)
  const sizeScale = H / REFERENCE_HEIGHT
  const vary = (v) => Math.max(0.05, 1 + (rng() * 2 - 1) * v * chaos)
  const e = spec.emitter
  const count = Math.max(1, Math.round(e.count))
  const emitWindow = e.duration * (1 - clamp01(e.explosiveness))
  const out = []
  for (let i = 0; i < count; i++) {
    const ox = e.shape === 'point' ? e.x * W : e.x * W + (rng() - 0.5) * e.width * W
    const oy = e.shape === 'area' ? e.y * H + (rng() - 0.5) * e.height * H : e.y * H
    const dir = (e.angle - 90) * DEG + (rng() - 0.5) * e.spread * DEG
    const speed = spec.launch.power * vary(spec.launch.powerVar) * sizeScale
    out.push({
      x: ox, y: oy,
      vx: Math.cos(dir) * speed, vy: Math.sin(dir) * speed,
      rot: rng() * 360,
      spin: spec.rotation.spin * vary(spec.rotation.spinVar) * (rng() < 0.5 ? -1 : 1),
      flut: rng() * TAU,
      flutSpeed: spec.rotation.flutter * vary(spec.rotation.flutterVar) * TAU,
      size: Math.max(0.5, spec.shape.size * vary(spec.shape.sizeVar) * sizeScale),
      shape: pickShape(spec, rng()),
      color: colors[Math.floor(rng() * colors.length) % colors.length],
      birth: (i / count) * emitWindow,
      life: Math.max(0.05, spec.life.life * vary(spec.life.lifeVar)),
      swayPhase: rng() * TAU, n1: rng() * TAU, n2: rng() * TAU,
    })
  }
  return out
}

function integrate(spec, particles, t, dt, H) {
  const p = spec.physics
  const sizeScale = H / REFERENCE_HEIGHT
  const gravity = p.gravity * sizeScale
  const wind = p.wind * sizeScale
  const turbulence = p.turbulence * sizeScale
  const swayAmp = p.swayAmp * sizeScale
  const damping = Math.pow(1 - Math.min(0.99, Math.max(0, p.drag)), dt)
  for (const q of particles) {
    const age = t - q.birth
    if (age < 0 || age > q.life) continue
    const wander = turbulence * Math.sin(age * 1.7 + q.n1) * Math.cos(age * 2.3 + q.n2)
    q.vx += (wind + wander) * dt
    q.vy += gravity * dt
    q.vx *= damping
    q.vy *= damping
    const sway = swayAmp * Math.sin(age * p.swayFreq * TAU + q.swayPhase)
    q.x += (q.vx + sway) * dt
    q.y += q.vy * dt
    q.rot += q.spin * dt
    q.flut += q.flutSpeed * dt
  }
}

function shade(hex, k) {
  const m = /^#?([0-9a-f]{6})$/i.exec(String(hex).trim())
  if (!m) return hex
  const v = parseInt(m[1], 16)
  return 'rgb(' + Math.round(((v >> 16) & 255) * k) + ',' +
                  Math.round(((v >> 8) & 255) * k) + ',' +
                  Math.round((v & 255) * k) + ')'
}

function roundRect(ctx, x, y, w, h, r) {
  const rr = Math.min(r, w / 2, h / 2)
  ctx.beginPath()
  ctx.moveTo(x + rr, y)
  ctx.arcTo(x + w, y, x + w, y + h, rr)
  ctx.arcTo(x + w, y + h, x, y + h, rr)
  ctx.arcTo(x, y + h, x, y, rr)
  ctx.arcTo(x, y, x + w, y, rr)
  ctx.closePath()
}

function drawPiece(ctx, shape, size, ratio) {
  if (shape === 'circle') {
    ctx.beginPath(); ctx.arc(0, 0, size * 0.42, 0, TAU); ctx.fill(); return
  }
  if (shape === 'ribbon') {
    const w = size * 0.3, h = size * Math.max(0.6, ratio * 2.2)
    roundRect(ctx, -w / 2, -h / 2, w, h, w / 2); ctx.fill(); return
  }
  if (shape === 'triangle') {
    const s = size * 0.62
    ctx.beginPath(); ctx.moveTo(0, -s); ctx.lineTo(s * 0.9, s * 0.7)
    ctx.lineTo(-s * 0.9, s * 0.7); ctx.closePath(); ctx.fill(); return
  }
  const w = size, h = size * ratio
  roundRect(ctx, -w / 2, -h / 2, w, h, Math.min(w, h) * 0.18)
  ctx.fill()
}

function draw(ctx, spec, particles, t, W, H, transparent) {
  const life = spec.life
  ctx.save()
  if (transparent && !spec.canvas.trail) {
    ctx.clearRect(0, 0, W, H)
  } else if (spec.canvas.trail > 0) {
    ctx.globalAlpha = 1 - clamp01(spec.canvas.trail)
    ctx.fillStyle = spec.canvas.background
    ctx.fillRect(0, 0, W, H)
    ctx.globalAlpha = 1
  } else {
    ctx.fillStyle = spec.canvas.background
    ctx.fillRect(0, 0, W, H)
  }
  for (const q of particles) {
    const age = t - q.birth
    if (age < 0 || age > q.life) continue
    const n = clamp01(age / q.life)
    const fadeIn = life.fadeIn > 0 ? clamp01(age / life.fadeIn) : 1
    const fadeOut = life.fadeOut > 0 ? clamp01((q.life - age) / life.fadeOut) : 1
    const alpha = ease(life.fadeEase, Math.min(fadeIn, fadeOut)) * spec.look.opacity
    if (alpha <= 0.002) continue
    const grow = life.scaleStart + (life.scaleEnd - life.scaleStart) * ease(life.scaleEase, n)
    const size = q.size * Math.max(0, grow)
    if (size <= 0.2) continue
    const tumble = Math.cos(q.flut)
    const angle = spec.rotation.alignToVelocity
      ? Math.atan2(q.vy, q.vx) + Math.PI / 2
      : q.rot * DEG
    ctx.save()
    ctx.globalAlpha = alpha
    ctx.translate(q.x, q.y)
    ctx.rotate(angle)
    ctx.scale(Math.max(0.02, Math.abs(tumble)), 1)
    ctx.fillStyle = spec.look.shine ? shade(q.color, 0.55 + 0.45 * Math.abs(tumble)) : q.color
    drawPiece(ctx, q.shape, size, spec.shape.ratio)
    ctx.restore()
  }
  ctx.restore()
}

export function duration(spec) {
  const e = spec.emitter
  const emitWindow = e.duration * (1 - clamp01(e.explosiveness))
  const longest = spec.life.life * (1 + spec.life.lifeVar * Math.max(0, spec.random.chaos))
  return Math.max(0.2, emitWindow + longest)
}

/**
 * Run the effect on a canvas.
 * @param {HTMLCanvasElement} canvas
 * @param {{spec?: object, loop?: boolean, speed?: number, transparent?: boolean,
 *          respectReducedMotion?: boolean, onComplete?: () => void}} [options]
 * @returns {() => void} stop
 */
export function confetti(canvas, options = {}) {
  const spec = options.spec || CONFIG
  const loop = options.loop === true
  const speed = options.speed || 1
  const transparent = options.transparent === true
  const respect = options.respectReducedMotion !== false
  const ctx = canvas.getContext('2d')
  if (!ctx) return () => {}

  if (respect && window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
    return () => {}
  }

  const total = duration(spec)
  let raf = 0
  let stopped = false
  let W = 0, H = 0, particles = [], t = 0, last = 0

  function resize() {
    const dpr = Math.min(window.devicePixelRatio || 1, 2)
    const rect = canvas.getBoundingClientRect()
    const w = Math.max(1, Math.round((rect.width || canvas.width) * dpr))
    const h = Math.max(1, Math.round((rect.height || canvas.height) * dpr))
    if (w === canvas.width && h === canvas.height && particles.length) return
    canvas.width = w
    canvas.height = h
    W = w
    H = h
    // Rebuild and replay to the current time: deterministic, so it stays continuous.
    particles = build(spec, W, H)
    let simT = 0
    while (simT < t - 1e-9) {
      const step = Math.min(FIXED_DT, t - simT)
      integrate(spec, particles, simT, step, H)
      simT += step
    }
  }

  const ro = typeof ResizeObserver === 'function' ? new ResizeObserver(resize) : null
  if (ro) ro.observe(canvas)
  resize()

  function frame(now) {
    if (stopped) return
    if (!last) last = now
    const dt = Math.min(0.05, ((now - last) / 1000) * speed)
    last = now
    let remaining = dt
    while (remaining > 1e-9) {
      const step = Math.min(FIXED_DT, remaining)
      integrate(spec, particles, t, step, H)
      t += step
      remaining -= step
    }
    draw(ctx, spec, particles, t, W, H, transparent)
    if (t >= total) {
      if (loop) {
        t = 0
        particles = build(spec, W, H)
      } else {
        stopped = true
        if (ro) ro.disconnect()
        if (options.onComplete) options.onComplete()
        return
      }
    }
    raf = requestAnimationFrame(frame)
  }
  raf = requestAnimationFrame(frame)

  return function stop() {
    stopped = true
    cancelAnimationFrame(raf)
    if (ro) ro.disconnect()
  }
}
